blank_issues_enabled: false
contact_links:
  - name: Security report
    url: https://github.com/LUC4N3X/stremio-leviathan-addon/security/advisories/new
    about: Report private security issues here.
